### ISSUE TITLE
 'AbortController' is not defined

### ISSUE THREAD

**Issue by virtusavivek** [vectorgraphics/asymptote-server#3]
Hi,

I tried to set up the asymptote server in a dedicated Instance, But I'm getting some exceptions in react build. I was using the last release in your repo. 

There is no import statement for AbortController

Please check the attachment.

![image](https://user-images.githubusercontent.com/79599701/126908011-b8324bdd-d9d4-4138-98a1-a7207b6a11df.png)

Thanks

**Comment by pedram-emami** [comment]
The error should be related to the node version. Please update your node to the latest stable version (>= 14.17.0).
