### ISSUE TITLE
Getting CORS

### ISSUE THREAD

**Issue by SophiaRebecca12** [vectorgraphics/asymptote-server#4]

**Comment by SophiaRebecca12** [comment]
#This is the code 

var _post_data = {
            "codeOption": false,
            "codeText": asy_code,
            "isUpdated": false,
            "outputOption": true,
            "reqType": "run",
            "requestedOutformat": "png",
            "workspaceId": 1,
            "workspaceName": "ta"
        }
        if (preDownload) {
            _post_data['isUpdated'] = true;
            _post_data['reqType'] = "preDownloadRun";
        }
        $.ajax({
            type: "POST",
            url: "https://example.com",
            data: JSON.stringify(_post_data),
            dataType: 'text',
            crossDomain: true,
            cache: false,
            beforeSend: function() {
                $("#loading").show();
            },
            success: function(data) {
                console.log(data);
                $("#loading").hide();
                if (data) {
                    if (preDownload) {
                        var asy_img_url = "https://www.example.com" + $("#output_asy_path").val() + ".png";
                        // $("#preview_output_img_url").attr('src', asy_img_url);
                        $("#asy_img_url").val(asy_img_url);
                        if (callback) {
                            callback();
                        }
                    } else {
                        var pos = data.toString().indexOf('/clients/');
                        var _path = data.substring(pos);
                        path = path.replace('::', '');
                        var output_asy_path = _path.replace(".html", "");
                        path = "https://www.example.com" + path;
                        $("#iframe_asy_output").attr('src', _path);
                        $("#output_asy_path").val(output_asy_path);
                        var asy_img_url = "https://www.example.com" + $("#output_asy_path").val() + ".png";
                        $("#asy_img_url").val(asy_img_url);
                    }
                } else {
                    alert("Oops! something wrong server");
                }
            },
            error: function(err) {
                console.log(err);
            },
            failure: function(errMsg) {
                $("#loading").hide();
                alert("Oops! something wrong server");
            }
        });


Example Domain
https://example.com

Example Domain
https://www.example.com


GitHub
https://github.com

#These are the errors we are facing

![error](https://user-images.githubusercontent.com/74983213/130364360-0f6e0438-6903-4cd4-8f8d-13038f48751e.png)

**Comment by johncbowman** [comment]
Can you please explain what you are trying to do?

If you are looking for a command-line interface to Asymptote, try
 
curl --data-binary 'import venn;' 'asymptote.ualberta.ca:10007?f=svg' | display -

curl --data-binary @/usr/local/share/doc/asymptote/examples/Klein.asy 'asymptote.ualberta.ca:10007' -o Klein.html

**Comment by SophiaRebecca12** [comment]
> #This is the code
> 
> var _post_data = { "codeOption": false, "codeText": asy_code, "isUpdated": false, "outputOption": true, "reqType": "run", "requestedOutformat": "png", "workspaceId": 1, "workspaceName": "ta" } if (preDownload) { _post_data['isUpdated'] = true; _post_data['reqType'] = "preDownloadRun"; } $.ajax({ type: "POST", url: "https://example.com", data: JSON.stringify(_post_data), dataType: 'text', crossDomain: true, cache: false, beforeSend: function() { $("#loading").show(); }, success: function(data) { console.log(data); $("#loading").hide(); if (data) { if (preDownload) { var asy_img_url = "https://www.example.com" + $("#output_asy_path").val() + ".png"; // $("#preview_output_img_url").attr('src', asy_img_url); $("#asy_img_url").val(asy_img_url); if (callback) { callback(); } } else { var pos = data.toString().indexOf('/clients/'); var _path = data.substring(pos); path = path.replace('::', ''); var output_asy_path = _path.replace(".html", ""); path = "https://www.example.com" + path; $("#iframe_asy_output").attr('src', _path); $("#output_asy_path").val(output_asy_path); var asy_img_url = "https://www.example.com" + $("#output_asy_path").val() + ".png"; $("#asy_img_url").val(asy_img_url); } } else { alert("Oops! something wrong server"); } }, error: function(err) { console.log(err); }, failure: function(errMsg) { $("#loading").hide(); alert("Oops! something wrong server"); } });
> 
> Example Domain https://example.com
> 
> Example Domain https://www.example.com
> 
> GitHub https://github.com
> 
> #These are the errors we are facing
> 
> ![error](https://user-images.githubusercontent.com/74983213/130364360-0f6e0438-6903-4cd4-8f8d-13038f48751e.png)

Issue resolved by adding CORS modules in the node.js application

**Comment by johncbowman** [comment]
Could you please create a pull request. Thanks!

**Comment by Sophia-Rebecca12** [comment]
This is a screenshot of http://asymptote.ualberta.ca:10007/
![image](https://user-images.githubusercontent.com/74983213/163227256-9e029a9d-487f-411b-a3fd-fa52ee8d22f8.png)
And below are screenshots of the site which is replicated from the same code on docker.
https://asyf.virtusasystems.com/
![image](https://user-images.githubusercontent.com/74983213/163228834-527f0904-07a0-4aeb-9038-507d30e2af7d.png)
But https://asyf.virtusasystems.com:10007/ says can't be reached.
![image](https://user-images.githubusercontent.com/74983213/163228924-4b048421-4fa3-4fbb-afe0-edd9ef5c5464.png)
