### ISSUE TITLE
Port 10007, unable to connect

### ISSUE THREAD

**Issue by SophiaRebecca12** [vectorgraphics/asymptote-server#5]
This is a screenshot of http://asymptote.ualberta.ca:10007/
![image](https://user-images.githubusercontent.com/74983213/163227256-9e029a9d-487f-411b-a3fd-fa52ee8d22f8.png)
And below are screenshots of the site which is replicated from the same code on docker.
https://asyf.virtusasystems.com/
![image](https://user-images.githubusercontent.com/74983213/163228834-527f0904-07a0-4aeb-9038-507d30e2af7d.png)
But https://asyf.virtusasystems.com:10007/ says can't be reached.
![image](https://user-images.githubusercontent.com/74983213/163228924-4b048421-4fa3-4fbb-afe0-edd9ef5c5464.png)

**Comment by johncbowman** [comment]
The Asymptote Web Application doesn't use port 10007. You must be thinking of the remote command-line interface for Asymptote:

https://github.com/vectorgraphics/asymptote-http-server
